let
    Source = Excel.Workbook(File.Contents("C:\Users\balaj\Downloads\Store+Data.xlsx"), null, true),
    Sheet3_Sheet = Source{[Item="Sheet3",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet3_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date (dd/mm/yyyy)", type date}, {"CustomerID", type text}, {"PromotionID", type text}, {"Product ID", type text}, {"Units Sold", Int64.Type}, {"Price Per Unit", type any}, {"Total Sales", type any}, {"Discount Percentage", type any}, {"Discount Value", type any}, {"Net Sales", type any}}),
    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Product ID"}, #"Dim Product", {"ProductID"}, "Dim Product", JoinKind.LeftOuter),
    #"Expanded Dim Product" = Table.ExpandTableColumn(#"Merged Queries", "Dim Product", {"Price Per Unit (INR)"}, {"Dim Product.Price Per Unit (INR)"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Dim Product",{"Price Per Unit"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Dim Product.Price Per Unit (INR)", "Price Per Unit"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales", "Discount Percentage", "Discount Value", "Net Sales"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "Total Sales  ", each [Units Sold] * [Price Per Unit]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Total Sales  ", Int64.Type}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"Total Sales"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns1",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales  ", "Discount Percentage", "Discount Value", "Net Sales"}),
    #"Merged Queries1" = Table.NestedJoin(#"Reordered Columns1", {"PromotionID"}, #"Dim Promotion", {"PromotionID"}, "Dim Promotion", JoinKind.LeftOuter),
    #"Expanded Dim Promotion" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Promotion", {"Percentage"}, {"Dim Promotion.Percentage"}),
    #"Replaced Value" = Table.ReplaceValue(#"Expanded Dim Promotion",null,0,Replacer.ReplaceValue,{"Dim Promotion.Percentage"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Replaced Value",{"Discount Percentage"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns2",{{"Dim Promotion.Percentage", "Discount Percentage"}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Renamed Columns1",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales  ", "Discount Percentage", "Discount Value", "Net Sales"}),
    #"Added Custom1" = Table.AddColumn(#"Reordered Columns2", "Discount", each ([#"Total Sales  "]*[Discount Percentage])/100),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Discount", type number}}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Changed Type2",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales  ", "Discount Percentage", "Discount", "Discount Value", "Net Sales"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns3",{"Discount Value"}),
    #"Added Custom2" = Table.AddColumn(#"Removed Columns3", "Net Sales    ", each [#"Total Sales  "]-[Discount]),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom2",{{"Net Sales    ", type number}}),
    #"Removed Columns4" = Table.RemoveColumns(#"Changed Type3",{"Net Sales"}),
    #"Added Custom3" = Table.AddColumn(#"Removed Columns4", "Profit Column", each 0.1*[#"Net Sales    "]),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom3",{{"Profit Column", type number}}),
    #"Added Index" = Table.AddIndexColumn(#"Changed Type4", "Index", 1, 1, Int64.Type),
    #"Reordered Columns4" = Table.ReorderColumns(#"Added Index",{"Index", "Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales  ", "Discount Percentage", "Discount", "Net Sales    ", "Profit Column"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns4",{{"Index", "Order ID"}}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Order ID", type text}})
in
    #"Changed Type5"